import '/github/kite9-org/kite9/templates/containers/containers.js?v=v0.15'
import '/github/kite9-org/kite9/templates/grid/grid.js?v=v0.15'
import '/github/kite9-org/kite9/templates/labels/labels.js?v=v0.15'
import '/github/kite9-org/kite9/templates/links/links.js?v=v0.15'
import '/github/kite9-org/kite9/templates/votes/votes.js?v=v0.15'
