
name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: '., bets, complexity, estimating, misc, overview, risks, thinking, actions'
        max-depth: 1
        use-quiet-mode: yes
